spring.application.name=FleetEx
spring.datasource.source.url=jdbc:sqlserver://192.168.0.161:1433;DatabaseName=SparcsN4_FMS;encrypt=true;trustServerCertificate=true;
spring.datasource.dest.url=jdbc:sqlserver://192.168.0.161:1433;DatabaseName=TestSTAGING;encrypt=true;trustServerCertificate=true;
spring.datasource.url=jdbc:sqlserver://192.168.0.161:1433;DatabaseName=TestSTAGING;encrypt=true;trustServerCertificate=true;
spring.datasource.username=Ramasamy
spring.datasource.password=XWBt#z@P
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Spring Batch configuration
#spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
spring.batch.jdbc.platform= sqlserver
#spring.batch.jdbc.table-prefix=dbo.

fleet.source.db=SparcsN4_FMS
fleet.target.db=TestSTAGING
fleet.source.schema=dbo
fleet.target.schema=dbo

# Logging hints
logging.file.name=D:\\Project\\Fleet Processor\\applogs\\app.log
logging.level.root=DEBUG`
server.port=8080

# Multipart configuration for large files
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB